config/routes.rb
Rails.application.routes.draw do
  #get 'users/index'

  get 'welcome/index'
  resources :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
   validates :name, presence: true, length: { minimum: 3 }
   validates :email, presence: true, length: { minimum: 5 },format: { without: /\s/ },uniqueness: true
   validates :phone_no, presence: true, length: { is: 10},numericality: true
   validates :dob, presence: true
    validates :password, presence: true, length: { minimum: 2}, confirmation: true
    validates :password_confirmation, presence: true, length: { minimum: 2}

    before_save :correct
    def correct
    name.upcase!
    email.downcase!
    end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
     @users = User.all
    end
     def new
      @user = User.new
  end
    def show
        @user = User.find(params[:id])
    end
    
  
   def create
  	#render plain: params[:user].inspect
  	@user = User.new(user_params)
    if @user.save
   redirect_to @user
 else 
  render 'new'
  	end
  end
  	private
  	def user_params
  		params.require(:user).permit(:name, :email, :phone_no, :dob, :password, :password_confirmation)
     end

     
    # def show
    # @user=User.find(params[:id])
    # end	
 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<center><h1>Sign Up</h1>
  <%= form_for :user, url: users_path do |f| %> 
   <p>
   <%= f.label :name%><br>
   <%= f.text_field :name , placeholder: "Enter Name",autofocus: true %>
  </p>
 <p>
   <%= f.label :email%><br>
   <%= f.email_field :email , placeholder: "Enter email",autofocus: true %>
  </p>
  <p>
   <%= f.label :phone_no %><br>
    <%= f.telephone_field :phone_no, placeholder: "Enter Mobile no" %>
  </p>
   <p>
    <%= f.label :dob %><br>
   <%= f.date_field :dob, max: Date.today %>
  </p>
 
  <p>
   <%= f.label :password %><br>
   <%= f.password_field :password , placeholder: "Enter Password"%>
  </p>
  <p>
    <%= f.label :confirm_password %><br>
    <%= f.password_field :password_confirmation , placeholder: "Re-enter Password"%>
  </p>
 
  <p>
   <%= f.submit "submit",controller: 'users' %>
     <%= link_to 'Back' , welcome_index_path %></center>
  </p>
<% end %>

app/views/users/new.html.erb
<center><h1>Sign Up</h1>
  <%= form_for :user, url: users_path do |f| %> 
  <% if @user.errors.any? %>
  <br><div id="error_explanation">
    <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %></br>
  <p>
   <%= f.label :name%><br>
   <%= f.text_field :name , placeholder: "Enter Name",autofocus: true %>
  </p>
 <p>
   <%= f.label :email%><br>
   <%= f.email_field :email , placeholder: "Enter Email",autofocus: true %>
  </p>
  <p>
   <%= f.label :phone_no %><br>
    <%= f.telephone_field :phone_no, placeholder: "Enter Mobile no" %>
  </p>
   <p>
    <%= f.label :dob %><br>
   <%= f.date_field :dob, max: Date.today %>
  </p>
 
  <p>
   <%= f.label :password %><br>
   <%= f.password_field :password , placeholder: "Enter Password"%>
  </p>
  <p>
    <%= f.label :confirm_password %><br>
    <%= f.password_field :password_confirmation , placeholder: "Re-enter Password"%>
  </p>
 
  <p>
   <%= f.submit "submit",controller: 'users' %>
     <%= link_to 'Back' , welcome_index_path %>
  </p>
<% end %></center>

app/views/users/show.html.erb
<center><h2>REGISTRATION SUCCESSFULL<h2>
<%= link_to 'Back' , welcome_index_path %></center>

app/views/welcome/index.html.erb
<center><h1> WELCOME TO Sign Up PAGE<h1>
<h2>Press button to start <h2>
	<%= link_to 'SIGN UP', new_user_path %></center>